name: Jriv
favicon: null
layout_spectrum: 0.15472219442017376
typography_spectrum: 0.5807813049759716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5064881695434451
  lightness: 0.08407147950492799
  saturation: 0.7532187758479267
  rhythmicContrast: 0.2974816896021366
purpose: []
